# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0011_auto_20170321_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='last_name',
        ),
    ]
