# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0012_auto_20170321_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1 - 5 employees', '1 - 5 employees'), ('6 - 16 employees', '6 - 16 employees'), ('17 - 99 employees', '17 - 99 employees'), ('100 - 420 employees', '100 - 420 employees'), ('421 - 1000 employees', '421 - 1000 employees'), ('1001 - 5000 employees', '1001 - 5000 employees'), ('5000+ employees', '5000+ employees')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT-Software / Software Services', 'IT-Software / Software Services'), ('BPO / Call Centre / ITES', 'BPO / Call Centre / ITES'), ('Automobile / Auto Anciliary / Auto Components', 'Automobile / Auto Anciliary / Auto Components'), ('Accounting / Finance', 'Accounting / Finance'), ('Advertising / PR / MR / Event Management', 'Advertising / PR / MR / Event Management'), ('Agriculture / Dairy', 'Agriculture / Dairy'), ('Animation / Gaming', 'Animation / Gaming'), ('Architecture / Interior Design', 'Architecture / Interior Design'), ('Aviation / Aerospace Firms', 'Aviation / Aerospace Firms'), ('Banking / Financial Services / Broking', 'Banking / Financial Services / Broking'), ('Brewery / Distillery', 'Brewery / Distillery'), ('Broadcasting', 'Broadcasting'), ('Consumer Electronics / Appliances / Durables', 'Consumer Electronics / Appliances / Durables'), ('Education / Teaching / Training', 'Education / Teaching / Training'), ('Electricals / Switchgears', 'Electricals / Switchgears'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='openingdetails',
            name='industry',
            field=models.CharField(choices=[('IT-Software / Software Services', 'IT-Software / Software Services'), ('BPO / Call Centre / ITES', 'BPO / Call Centre / ITES'), ('Automobile / Auto Anciliary / Auto Components', 'Automobile / Auto Anciliary / Auto Components'), ('Accounting / Finance', 'Accounting / Finance'), ('Advertising / PR / MR / Event Management', 'Advertising / PR / MR / Event Management'), ('Agriculture / Dairy', 'Agriculture / Dairy'), ('Animation / Gaming', 'Animation / Gaming'), ('Architecture / Interior Design', 'Architecture / Interior Design'), ('Aviation / Aerospace Firms', 'Aviation / Aerospace Firms'), ('Banking / Financial Services / Broking', 'Banking / Financial Services / Broking'), ('Brewery / Distillery', 'Brewery / Distillery'), ('Broadcasting', 'Broadcasting'), ('Consumer Electronics / Appliances / Durables', 'Consumer Electronics / Appliances / Durables'), ('Education / Teaching / Training', 'Education / Teaching / Training'), ('Electricals / Switchgears', 'Electricals / Switchgears'), ('Others', 'Others')], max_length=100),
        ),
    ]
