# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0013_auto_20170323_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
