# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0014_auto_20170323_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingdetails',
            old_name='annual_ctc_max',
            new_name='job_location',
        ),
        migrations.RenameField(
            model_name='openingdetails',
            old_name='job_role',
            new_name='job_profile',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='annual_ctc_min',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='functional_area',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='location',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='number_of_vacancies',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='work_experienc_max',
        ),
        migrations.RemoveField(
            model_name='openingdetails',
            name='work_experienc_min',
        ),
        migrations.AddField(
            model_name='openingdetails',
            name='department',
            field=models.CharField(blank=True, choices=[('IT-Software / Software Services', 'IT-Software / Software Services'), ('BPO / Call Centre / ITES', 'BPO / Call Centre / ITES'), ('Automobile / Auto Anciliary / Auto Components', 'Automobile / Auto Anciliary / Auto Components'), ('Accounting / Finance', 'Accounting / Finance'), ('Advertising / PR / MR / Event Management', 'Advertising / PR / MR / Event Management'), ('Agriculture / Dairy', 'Agriculture / Dairy'), ('Animation / Gaming', 'Animation / Gaming'), ('Architecture / Interior Design', 'Architecture / Interior Design'), ('Aviation / Aerospace Firms', 'Aviation / Aerospace Firms'), ('Banking / Financial Services / Broking', 'Banking / Financial Services / Broking'), ('Brewery / Distillery', 'Brewery / Distillery'), ('Broadcasting', 'Broadcasting'), ('Consumer Electronics / Appliances / Durables', 'Consumer Electronics / Appliances / Durables'), ('Education / Teaching / Training', 'Education / Teaching / Training'), ('Electricals / Switchgears', 'Electricals / Switchgears'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openingdetails',
            name='job_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openingdetails',
            name='job_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openingdetails',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Fulltime/Part-time', 'Fulltime/Part-time'), ('Permanent/Temporary/Contract', 'Permanent/Temporary/Contract'), ('Apprenticeships/Internship/Volunteer ', 'Apprenticeships/Internship/Volunteer ')], max_length=100, null=True),
        ),
    ]
