# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-06 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuserprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='companyuserprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='companyuserprofile',
            name='last_name',
        ),
    ]
