# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0003_jobprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('IT-Software / Software Services', 'IT-Software / Software Services'), ('BPO / Call Centre / ITES', 'BPO / Call Centre / ITES'), ('Automobile / Auto Anciliary / Auto Components', 'Automobile / Auto Anciliary / Auto Components'), ('Accounting / Finance', 'Accounting / Finance'), ('Advertising / PR / MR / Event Management', 'Advertising / PR / MR / Event Management'), ('Agriculture / Dairy', 'Agriculture / Dairy'), ('Animation / Gaming', 'Animation / Gaming'), ('Architecture / Interior Design', 'Architecture / Interior Design'), ('Aviation / Aerospace Firms', 'Aviation / Aerospace Firms'), ('Banking / Financial Services / Broking', 'Banking / Financial Services / Broking'), ('Brewery / Distillery', 'Brewery / Distillery'), ('Broadcasting', 'Broadcasting'), ('Consumer Electronics / Appliances / Durables', 'Consumer Electronics / Appliances / Durables'), ('Education / Teaching / Training', 'Education / Teaching / Training'), ('Electricals / Switchgears', 'Electricals / Switchgears'), ('Others', 'Others')], max_length=100)),
                ('job_type', models.CharField(choices=[('Fulltime/Part-time', 'Fulltime/Part-time'), ('Permanent/Temporary/Contract', 'Permanent/Temporary/Contract'), ('Apprenticeships/Internship/Volunteer ', 'Apprenticeships/Internship/Volunteer ')], max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_start_date', models.DateTimeField()),
            ],
        ),
    ]
