# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0004_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='job_location',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='job_type',
        ),
        migrations.AddField(
            model_name='employe',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='mark',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
