# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0005_auto_20170409_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='degree',
            field=models.CharField(default='B.tech', max_length=100),
            preserve_default=False,
        ),
    ]
