# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0007_auto_20170503_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserprofile',
            name='compant_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
