# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0011_auto_20170510_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyuserprofile',
            old_name='description',
            new_name='short_introduction',
        ),
        migrations.AddField(
            model_name='companyuserprofile',
            name='founded_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
