# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0012_auto_20170511_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='job_period',
            field=models.CharField(blank=True, choices=[('Years', 'Years'), ('Months', 'Months'), ('Weeks', 'Weeks')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='job_period_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='min_degree_qulification',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='salary_type',
            field=models.CharField(choices=[('Per Annum', 'Per Annum'), ('Per Hour', 'Per Hour')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Volunteer', 'Volunteer'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=100),
        ),
    ]
