# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0014_auto_20170518_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='industry_experience_months',
            new_name='industry_exp_months',
        ),
        migrations.RenameField(
            model_name='jobprofile',
            old_name='industry_experience_year',
            new_name='industry_exp_year',
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='sponsor_visa',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100),
        ),
    ]
