# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0015_auto_20170523_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='industry_exp_months',
            field=models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='industry_exp_year',
            field=models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14'), (b'15', b'15'), (b'16', b'16'), (b'17', b'17'), (b'18', b'18'), (b'19', b'19')], max_length=100),
        ),
    ]
