# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0016_auto_20170523_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='tech_skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
