# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0018_auto_20170525_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='subject_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
