# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0019_auto_20170526_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='start_date',
            field=models.DateField(),
        ),
    ]
