# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0022_auto_20170608_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='industry_exp_year',
            field=models.CharField(blank=True, choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14'), (b'15', b'15'), (b'16', b'16'), (b'17', b'17'), (b'18', b'18'), (b'19', b'19')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('Per Annum', 'Per Annum'), ('Per Hour', 'Per Hour')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='sponsor_visa',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='work_experience_year',
            field=models.CharField(blank=True, choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14'), (b'15', b'15'), (b'16', b'16'), (b'17', b'17'), (b'18', b'18'), (b'19', b'19')], max_length=100, null=True),
        ),
    ]
