# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0025_employe_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='mark',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='employe',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('send invitation', 'send invitation'), ('invitation accepted', 'invitation accepted')], default='online', max_length=100),
        ),
    ]
